const Projects = [
    {
        "id": 2,
        "featured": false,
        "name": "Pommo",
        "uniqueid": "jwcdr2r1",
        "year": "July 2022",
        "category": "Case Studies",
        "type": "UX Design, Desktop App Design",
        "coverimage": "/images/projects/jwcdr2r1/65510539dad3d.webp",
        "coverhash": "LIIE|g0000~q00%MRjRj00~q-;IU",
        "title": "Empowering remote tech workers in Nigeria to be more productive and stay focused by reducing distractions.",
        "description": "Pommo is focused on empowering remote tech workers in Nigeria to stay focused by minimizing distractions. They aim to provide users with the tools and resources they need to increase their productivity and achieve their professional goals.",
        "imageSrc": "images/jwcdr2r1/xfxph0qydc2pi9rqulej.webp"
    },
    {
        "id": 6,
        "featured": true,
        "name": "TGIT",
        "uniqueid": "jwcd04r1",
        "year": "June 2023",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "coverimage": "/images/projects/jwcd04r1/6550ecff98f66.webp",
        "coverhash": "LJK-Um_3~Vt501t8D%ay^*WBD+WD",
        "title": "Making access to professional courses less confusing and easier to navigate through for engineers.",
        "description": "Thompson and Grace Insitute of Technology is dedicated to simplifying the process of finding IT professional courses for engineering professionals and making their journey easy for them to navigate through.",
        "imageSrc": "images/jwcd04r1/qyoticyz7g1nukukdkpk.webp"
    },
    {
        "id": 8,
        "featured": false,
        "name": "Hotel Capricorn",
        "uniqueid": "jwa4ed01",
        "year": "December 2021",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "coverimage": "/images/projects/jwa4ed01/6551f43a99d7e.webp",
        "coverhash": "LTPi-U%2~VIU%Ms:M{Rk_2RjD*xt",
        "title": "Elevating user experiences for business and leisure travellers through seamless hotel reservations.",
        "description": "Hotel Capricorn is an exploration for a premium hotel reservation experience, designed to cater to the needs of both business and leisure travelers. The conceptualized seamless booking process is centered on ensuring guest satisfaction, so users can expect nothing but the best.",
        "imageSrc": "images/jwa4ed01/qgqlgw6ui8wcknlh0rms.webp"
    },
    {
        "id": 9,
        "featured": true,
        "name": "The Food Mag",
        "uniqueid": "jwacery1",
        "year": "August 2023",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "coverimage": "/images/projects/jwacery1/6551f4b61080e.webp",
        "coverhash": "LQK^mHHXMyBj~WrXM{xI4;O=-Uw4",
        "title": "Designing a captivating reading experience for an online food magazine.",
        "description": "Imagine a world where food is not just something you eat, but an experience that engages all your senses. The Food Mag brings this world to life by providing an immersive experience into the exciting world of culinary arts.",
        "imageSrc": "images/jwacery1/a7uly1bj67tojzn9tnry.webp"
    },
    {
        "id": 3,
        "featured": true,
        "name": "LunarLuxury",
        "uniqueid": "jwfe0431",
        "year": "January 2022",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "coverimage": "/images/projects/jwfe0431/64957cab2f8e4.webp",
        "coverhash": "LIOBuTs,}3WBEyae$*bv[8ofBrRk",
        "title": "Facilitating seamless explorations of travel destinations for luxury nomads.",
        "description": "LunarLuxury is here to make the travel experiences of luxury travellers seamless and unforgettable. They aim to help users easily explore the most exotic destinations, so users can indulge in the finest luxuries their choiced locations have to offer.",
        "imageSrc": "images/jwfe0431/kkpczc59epb7yxwg5qin.webp"
    },
    {
        "id": 5,
        "featured": false,
        "name": "UberEats",
        "uniqueid": "jw562312",
        "year": "September 2022",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "coverimage": "/images/projects/jw562312/6551f8ba92328.webp",
        "coverhash": "LNR3TVof~qWBs;t7kBNG~qWBITxa",
        "title": "Innovating UberEats for busy professionals, introducing recipe and meal planning features in the mobile app.",
        "description": "I had the opportunity to revamp the Uber Eats app by adding new features that focused on recipe and meal planning. With this addition, busy users could conveniently plan their meals ahead for the day or week. The primary objective was to eliminate the stress of meal planning after a busy day and provide users with the chance to learn new meal preparations and explore new cuisines.",
        "imageSrc": "images/jw562312/v7h0qd3fueu1firh1lba.webp"
    },
    {
        "id": 4,
        "featured": false,
        "name": "Thrive",
        "uniqueid": "jw39204a",
        "year": "August 2021",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "coverimage": "/images/projects/jw39204a/6550f3a624431.webp",
        "coverhash": "LLGSZ9tR00D%J6Rjn+oz00ae~qxv",
        "title": "Helping Thrive simplify the process of targeted Ad planning for small and medium-sized enterprises (SMEs) in Nigeria.",
        "description": "Growing in Nigeria's competitive business environment is challenging for SMEs. Effective targeted ad planning is crucial but can be complex and time-consuming. Thrive simplifies this process with a user-friendly platform and manages the creation and implementation of ad campaigns to reach their desired audience. Thrive has a goal to help SMEs grow and succeed in the Nigerian market.",
        "imageSrc": "images/jw39204a/ubixhxflhlyh1zuszfgp.webp"
    },
    {
        "id": 1,
        "featured": true,
        "name": "FirstMedtrade",
        "uniqueid": "jw09a422",
        "year": "February 2023",
        "category": "Case Studies",
        "type": "UX Design, Website Redesign",
        "coverimage": "/images/projects/jw09a422/5ece4797eaf5e.webp",
        "coverhash": "LNIi;Qa}05og?FfQNHj[04j[~RWB",
        "title": "Simplifying online access to medical supplies for 1,000+ hospitals and patients.",
        "description": "FirstMedtrade is an e-commerce platform that seeks to redefine the way hospitals, doctors, and patients access and procure essential medical equipment and consumables from local vendors and international manufacturers.",
        "imageSrc": "images/jw09a422/cottzkkv89lmt28yx4jq.webp"
    },
    {
        "id": 7,
        "featured": false,
        "name": "TVNR",
        "uniqueid": "jw032qa1",
        "year": "September 2021",
        "category": "Visual Design",
        "type": "UI Design",
        "coverimage": "/images/projects/jw032qa1/65520d74f240e.webp",
        "coverhash": "L9Bh0}9F00_NoyRjay%M00.8^m4n",
        "title": "Crafting a purposeful platform for Breast Cancer Advocacy through an intuitive and compassionate user experience.",
        "description": "The Victoria Nwaeke Cancer Foundation is an NGO focused on amplifying the voices of those affected by Breast Cancer and ensuring that they are heard. Their online platform is designed to facilitate Breast Cancer advocacy with care and compassion at its core.",
        "imageSrc": "images/jw032qa1/m6hmebi3faindigzx6kz.webp"
    }
]

export default Projects;