const Projects = [
    {
        "id": 1,
        "featured": true,
        "name": "FirstMedtrade",
        "industry": "Health-tech",
        "uniqueid": "jw09a422",
        "year": "February 2023",
        "category": "Case Studies",
        "type": "UX Design, Website Redesign",
        "casecoverimage": "/images/jw09a422/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Simplifying online access to medical supplies for healthcare seekers and providers.",
        "description": "FirstMedtrade aims to change the medical equipment and consumables procurement process for hospitals, doctors, and patients by providing a convenient e-commerce platform. The platform connects healthcare professionals and patients to local sellers and international manufacturers, making it easier to access the necessary medical supplies.\n\nWith the help of this platform, healthcare providers can quickly and efficiently procure medical equipment and consumables, ensuring that they are always well-stocked and prepared to provide quality care to patients. Additionally, patients can directly purchase the medical supplies they need via the platform, thereby avoiding the inconvenience of visiting a physical store or hospital.",
        "imageSrc": "images/jw09a422/cottzkkv89lmt28yx4jq.webp"
    },
    {
        "id": 2,
        "featured": true,
        "name": "TGIT",
        "industry": "Education",
        "uniqueid": "jwcd04r1",
        "year": "June 2023",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "casecoverimage": "/images/jwcd04r1/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Making access to professional courses less confusing and easier to navigate through for engineers.",
        "description": "Thompson and Grace Insitute of Technology is dedicated to simplifying the process of finding IT professional courses for engineering professionals and making their journey easy for them to navigate through.",
        "imageSrc": "images/jwcd04r1/qyoticyz7g1nukukdkpk.webp",
        "figma": "https://www.figma.com/proto/SUNvFTfeuudGNJfKIyD1rP/Institute?page-id=48%3A132&type=design&node-id=169-6118&viewport=248%2C73%2C0.02&t=HqULv5NbyhaFiznq-1&scaling=scale-down&starting-point-node-id=169%3A6118&mode=design"
    },
    {
        "id": 3,
        "featured": true,
        "name": "The Food Mag",
        "industry": "Lifestyle, Blog",
        "uniqueid": "jwacery1",
        "year": "August 2023",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "casecoverimage": "/images/jwacery1/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Elevating food content discovery and visual appeal for getaway tourists.",
        "description": "This project involved designing the landing page of a food magazine tailored for tourists. The primary aim was to create an immersive experience that would enhance the tourists' ability to find and engage with street food content. I executed various user-friendly navigation features and visually appealing design elements. By doing so, I aimed to create a sense of excitement and curiosity that would motivate users to engage with the content and discover new and exciting street food experiences.",
        "imageSrc": "images/jwacery1/a7uly1bj67tojzn9tnry.webp"
    },
    {
        "id": 4,
        "featured": false,
        "name": "Thrive",
        "industry": "SaaS",
        "uniqueid": "jw39204a",
        "year": "August 2021",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "casecoverimage": "/images/jw39204a/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Helping Thrive simplify the process of targeted Ad planning for small and medium-sized enterprises (SMEs) in Nigeria.",
        "description": "Growing in Nigeria's competitive business environment is challenging for SMEs. Effective targeted ad planning is crucial but can be complex and time-consuming. Thrive simplifies this process with a user-friendly platform and manages the creation and implementation of ad campaigns to reach their desired audience. Thrive has a goal to help SMEs grow and succeed in the Nigerian market.",
        "imageSrc": "images/jw39204a/ubixhxflhlyh1zuszfgp.webp",
        "figma": "https://www.figma.com/proto/vpeAMqcLw6yOTd39tV76rW/thrive.nig?page-id=0%3A1&type=design&node-id=23-72&viewport=278%2C276%2C0.05&t=xjnoajbOJ3ktE3rS-1&scaling=scale-down&starting-point-node-id=21%3A54&mode=design"
    },
    {
        "id": 5,
        "featured": false,
        "name": "UberEats",
        "industry": "Food delivery",
        "uniqueid": "jw562312",
        "year": "September 2022",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "casecoverimage": "/images/jw562312/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Innovating UberEats for busy professionals, introducing recipe and meal planning features in the mobile app.",
        "description": "Uber Eats is a food delivery service operated by Uber. I was involved in designing a test feature that enables users to plan their meals in advance. The concept behind the feature was to allow users to purchase groceries by specifying the food they want to eat and have them delivered straight to their homes. While there are several food delivery services available, only a few offer the option of selecting the best ingredients for the meals. This feature works great for those who prefer cooking their meals at home but lack the time to go grocery shopping.",
        "imageSrc": "images/jw562312/v7h0qd3fueu1firh1lba.webp",
        "figma": "https://www.figma.com/proto/CpHYkfFfeZYHqJpUJr0ApQ/Days-of-humble-beginnings-(EST-July-07%2C-21)?page-id=959%3A1934&type=design&node-id=31-5927&viewport=405%2C392%2C0.03&t=VQgQ2ikQ5HwoK1Uh-1&scaling=scale-down&starting-point-node-id=30%3A58&mode=design"
    },
    {
        "id": 6,
        "featured": false,
        "name": "LunarLuxury",
        "industry": "Hospitality, Lifestyle",
        "uniqueid": "jwfe0431",
        "year": "January 2022",
        "category": "Case Studies",
        "type": "UX Design, Website Design",
        "casecoverimage": "/images/jwfe0431/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Facilitating seamless explorations of travel destinations for luxury nomads.",
        "description": "LunarLuxury is here to make the travel experiences of luxury travellers seamless and unforgettable. They aim to help users easily explore the most exotic destinations, so users can indulge in the finest luxuries their choiced locations have to offer.",
        "imageSrc": "images/jwfe0431/kkpczc59epb7yxwg5qin.webp",
        "figma": "https://www.figma.com/proto/izTnj0S5UNXjuNT7LaXBUf/Website?page-id=0%3A1&type=design&node-id=3-6&viewport=483%2C183%2C0.24&t=ZzKpgAqmQ7g6BYrg-1&scaling=scale-down&starting-point-node-id=3%3A6&mode=design"
    },
    {
        "id": 7,
        "featured": false,
        "name": "TVNR",
        "industry": "Non-profit",
        "uniqueid": "jw032qa1",
        "year": "September 2021",
        "category": "Visual Design",
        "type": "UI Design",
        "casecoverimage": "/images/jw032qa1/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Crafting a purposeful platform for Breast Cancer Advocacy through an intuitive and compassionate user experience.",
        "description": "The Victoria Nwaeke Cancer Foundation is an NGO focused on amplifying the voices of those affected by Breast Cancer and ensuring that they are heard. Their online platform is designed to facilitate Breast Cancer advocacy with care and compassion at its core.",
        "imageSrc": "images/jw032qa1/m6hmebi3faindigzx6kz.webp",
        "figma": "https://www.figma.com/proto/EGS1uzrWYjLZTYbqxHNhVM/TVN-Foundation?page-id=0%3A1&type=design&node-id=375-706&viewport=371%2C316%2C0.05&t=dP7kbmHwlreHFm5g-1&scaling=scale-down&starting-point-node-id=375%3A706&mode=design"
    },
    {
        "id": 8,
        "featured": true,
        "name": "Hotel Capricorn",
        "industry": "Hospitality, Lifestyle",
        "uniqueid": "jwa4ed01",
        "year": "December 2021",
        "category": "Visual Design",
        "type": "UI Design, Design Exploration",
        "casecoverimage": "/images/jwa4ed01/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Elevating user experiences for business and leisure travellers through seamless hotel reservations.",
        "description": "Hotel Capricorn is an exploration for a premium hotel reservation experience, designed to cater to the needs of both business and leisure travelers. The conceptualized seamless booking process is centered on ensuring guest satisfaction, so users can expect nothing but the best.",
        "imageSrc": "images/jwa4ed01/qgqlgw6ui8wcknlh0rms.webp",
        "figma": "https://www.figma.com/proto/3eulIvomh9Kz0fBIvHeeJm/ClassWork?page-id=0%3A1&type=design&node-id=117-688&viewport=104%2C-715%2C0.14&t=q6XmjfgiDez3w1qD-1&scaling=scale-down&starting-point-node-id=117%3A688&mode=design"
    },
    {
        "id": 9,
        "featured": false,
        "name": "Pomo",
        "industry": "Productivity",
        "uniqueid": "jwcdr2r1",
        "year": "July 2022",
        "category": "Case Studies",
        "type": "UX Design, Desktop App Design",
        "casecoverimage": "/images/jwcdr2r1/case-study-cover.webp",
        "casecoverhash": "LCI6G.WA00bbRj00oL^,00oz~XWB",
        "title": "Empowering remote tech workers with ADHD to be more productive and focused.",
        "description": "Pomo is focused on empowering remote tech workers with ADHD to stay focused by minimizing distractions. Using the Pomodoro technique, Pomo tries to ahieve this by setting certain device restrictions that prevent them from using their devices for nything other than work for the period while the focus mode is running.",
        "imageSrc": "images/jwcdr2r1/xfxph0qydc2pi9rqulej.webp",
        "figma": "https://www.figma.com/proto/3eulIvomh9Kz0fBIvHeeJm/ClassWork?page-id=180%3A40182&type=design&node-id=257-2113&viewport=209%2C299%2C0.02&t=uKI6bhD2sYAi64Kw-1&scaling=scale-down&starting-point-node-id=1223%3A1179&mode=design"
    }
]

export default Projects;